/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    prompts: Prompt;
    'enrichment-history': EnrichmentHistory;
    'api-cache': ApiCache;
    services: Service;
    industries: Industry;
    personas: Persona;
    problems: Problem;
    solutions: Solution;
    locations: Location;
    'seo-pages': SeoPage;
    keywords: Keyword;
    testimonials: Testimonial;
    blog: Blog;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    prompts: PromptsSelect<false> | PromptsSelect<true>;
    'enrichment-history': EnrichmentHistorySelect<false> | EnrichmentHistorySelect<true>;
    'api-cache': ApiCacheSelect<false> | ApiCacheSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    problems: ProblemsSelect<false> | ProblemsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'seo-pages': SeoPagesSelect<false> | SeoPagesSelect<true>;
    keywords: KeywordsSelect<false> | KeywordsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'brand-dna': BrandDna;
  };
  globalsSelect: {
    'brand-dna': BrandDnaSelect<false> | BrandDnaSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Usuarios del equipo Guardman
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'sales' | 'seo_manager' | 'support') | null;
  avatar?: (number | null) | Media;
  phone?: string | null;
  isActive?: boolean | null;
  telegram?: {
    chatId?: string | null;
    username?: string | null;
    notificationsEnabled?: boolean | null;
    notifyOnNewLead?: boolean | null;
    notifyOnStatusChange?: boolean | null;
  };
  salesProfile?: {
    preferredZones?:
      | {
          zone?: ('oriente' | 'nororiente' | 'norte' | 'poniente' | 'suroriente' | 'sur' | 'centro') | null;
          id?: string | null;
        }[]
      | null;
    specializations?:
      | {
          persona?: string | null;
          id?: string | null;
        }[]
      | null;
    workingHours?: {
      start?: number | null;
      end?: number | null;
    };
    maxPendingLeads?: number | null;
  };
  stats?: {
    totalLeads?: number | null;
    convertedLeads?: number | null;
    conversionRate?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Gestión de Prompts modulares para GLM.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts".
 */
export interface Prompt {
  id: number;
  /**
   * Identificador único (ej. "generate_cluster_structure", "write_hero_section").
   */
  identifier: string;
  /**
   * Propósito de este prompt.
   */
  description?: string | null;
  /**
   * Instrucciones base para la IA (rol, formato, restricciones).
   */
  systemPrompt: string;
  /**
   * Template del prompt con variables inyectables (ej. {{location}}, {{service}}).
   */
  userPromptTemplate: string;
  /**
   * JSON Schema estricto que se espera recibir de respuesta.
   */
  expectedOutputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de auditoría de todas las interacciones con APIs (Serper, GLM).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrichment-history".
 */
export interface EnrichmentHistory {
  id: number;
  sourceCollection?: ('locations' | 'services' | 'problems' | 'seo-pages') | null;
  sourceId?: string | null;
  serperRawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  glmPromptIdentifier?: (number | null) | Prompt;
  glmResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tokensUsed?: number | null;
  wasSuccessful?: boolean | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Memoria Global: Interceptor de Peticiones a APIs Externas para ahorrar costos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-cache".
 */
export interface ApiCache {
  id: number;
  /**
   * La clave de caché, por ejemplo el Hash del prompt GLM o el query de Serper.
   */
  cacheKey: string;
  service: 'serper' | 'glm';
  response:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Servicios de seguridad ofrecidos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Ej: guardias-de-seguridad, monitoreo-24-7
   */
  slug: string;
  /**
   * Descripción breve para tarjetas y listados
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Emoji para mostrar en tarjetas
   */
  icon?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Características del servicio
   */
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        benefit?: string | null;
        id?: string | null;
      }[]
    | null;
  priceRange?: {
    min?: number | null;
    max?: number | null;
    billingPeriod?: ('month' | 'shift' | 'hour' | 'service') | null;
    hidePrice?: boolean | null;
  };
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedLocations?: (number | Location)[] | null;
  relatedIndustries?: (number | Industry)[] | null;
  relatedProblems?: (number | Problem)[] | null;
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mostrar en página principal
   */
  isHighlighted?: boolean | null;
  isActive?: boolean | null;
  /**
   * Menor número = aparece primero
   */
  order?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Comunas de la Región Metropolitana
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * Ingresa el nombre y guarda para generar contenido automáticamente
   */
  name: string;
  /**
   * Se genera automáticamente desde el nombre
   */
  slug?: string | null;
  region?: ('rm' | 'valparaiso') | null;
  geoZone?: ('oriente' | 'nororiente' | 'norte' | 'poniente' | 'suroriente' | 'sur' | 'centro' | 'aconcagua') | null;
  tier?: ('premium' | 'high' | 'medium' | 'emerging') | null;
  /**
   * Se genera automáticamente con IA
   */
  economicDriver?:
    | ('industrial' | 'corporativo_premium' | 'comercial_alta_densidad' | 'residencial_premium' | 'mixto_masivo')
    | null;
  decisionBuyerLocation?: (number | null) | Location;
  /**
   * Estado del pipeline de generación de contenido
   */
  enrichmentStatus?: ('pending' | 'in_progress' | 'completed' | 'failed') | null;
  /**
   * Se genera automáticamente con IA
   */
  characteristics?: string | null;
  population?: number | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Se genera automáticamente con IA
   */
  mainKeywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceAreas?:
    | {
        area?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mayor número = más importante para SEO
   */
  priorityScore?: number | null;
  isActive?: boolean | null;
  seo?: {
    /**
     * Se genera automáticamente con IA
     */
    metaTitle?: string | null;
    /**
     * Se genera automáticamente con IA
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Industrias que atendemos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  image?: (number | null) | Media;
  relatedServices?: (number | Service)[] | null;
  /**
   * Roles típicos en esta industria (relacionados a la colección Personas)
   */
  targetPersonas?: (number | Persona)[] | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Datos para contenido SEO
   */
  statistics?: {
    marketSize?: string | null;
    growthRate?: string | null;
    mainRisks?:
      | {
          risk?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  caseStudy?: (number | null) | Blog;
  isActive?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Personas objetivo (clientes ideales)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: number;
  name: string;
  slug: string;
  /**
   * Ej: Administrador de Condominio
   */
  title: string;
  description?: string | null;
  avatar?: (number | null) | Media;
  demographics?: {
    ageRange?: string | null;
    location?: string | null;
    incomeLevel?: ('premium' | 'high' | 'medium' | 'emerging') | null;
  };
  /**
   * Problemas estructurales que sufre este cliente (ligados a colección Problems)
   */
  painPoints?: (number | Problem)[] | null;
  needs?:
    | {
        need?: string | null;
        id?: string | null;
      }[]
    | null;
  goals?:
    | {
        goal?: string | null;
        id?: string | null;
      }[]
    | null;
  preferredServices?: (number | Service)[] | null;
  budgetRange?: {
    min?: number | null;
    max?: number | null;
  };
  decisionTimeline?: ('immediate' | 'short' | 'medium' | 'long') | null;
  /**
   * Keywords que usa esta persona
   */
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedIndustries?: (number | Industry)[] | null;
  communication?: {
    preferredChannel?: ('phone' | 'email' | 'whatsapp' | 'in_person') | null;
    tone?: ('formal' | 'semi_formal' | 'informal') | null;
  };
  /**
   * Puntos base para scoring de leads
   */
  scoring?: {
    baseScore?: number | null;
    urgencyWeight?: number | null;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Problemas de seguridad que buscan los clientes (keywords SEO)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems".
 */
export interface Problem {
  id: number;
  /**
   * Ej: Robos en condominios, Falta de seguridad
   */
  name: string;
  slug: string;
  /**
   * Descripción del problema para contenido SEO
   */
  description?: string | null;
  relatedServices?: (number | Service)[] | null;
  /**
   * Palabras clave relacionadas con este problema
   */
  keywords?:
    | {
        keyword?: string | null;
        intent?: ('informational' | 'commercial' | 'transactional') | null;
        volume?: ('high' | 'medium' | 'low') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Por qué el cliente busca este servicio
   */
  painPoints?:
    | {
        painPoint?: string | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Artículos del blog
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * Ej: como-elegir-servicio-seguridad
   */
  slug: string;
  /**
   * Breve descripción para tarjetas y SEO (160 caracteres)
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  category?: ('security-tips' | 'news' | 'case-studies' | 'guides' | 'business-security' | 'home-security') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedLocations?: (number | Location)[] | null;
  relatedServices?: (number | Service)[] | null;
  relatedProblems?: (number | Problem)[] | null;
  author?: (number | null) | User;
  seo?: {
    /**
     * Título para SEO (60 caracteres máx)
     */
    metaTitle?: string | null;
    /**
     * Descripción para SEO (160 caracteres máx)
     */
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'review' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  featured?: boolean | null;
  views?: number | null;
  /**
   * Tiempo estimado de lectura
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Soluciones específicas para cada necesidad
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: string | null;
  image?: (number | null) | Media;
  industry?: (number | null) | Industry;
  targetPersonas?: (number | Persona)[] | null;
  relatedServices?: (number | Service)[] | null;
  includes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        benefit?: string | null;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    min?: number | null;
    max?: number | null;
    billingPeriod?: ('month' | 'service') | null;
    hidePrice?: boolean | null;
  };
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  isHighlighted?: boolean | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Páginas SEO geolocalizadas
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-pages".
 */
export interface SeoPage {
  id: number;
  title: string;
  /**
   * Ej: seguridad-las-condes-guardias
   */
  slug: string;
  pageType:
    | 'location'
    | 'service'
    | 'industry'
    | 'persona'
    | 'service-location'
    | 'industry-location'
    | 'persona-location'
    | 'problem-location';
  /**
   * Clasificación estructural dentro del Topic Cluster.
   */
  clusterRole?: ('hub' | 'spoke' | 'local_bottom_funnel') | null;
  /**
   * Define la página padre a la que apunta y pertenece.
   */
  parentHub?: (number | null) | SeoPage;
  location?: (number | null) | Location;
  service?: (number | null) | Service;
  industry?: (number | null) | Industry;
  persona?: (number | null) | Persona;
  /**
   * El tomador de decisiones o Buyer Persona al que apunta el contenido B2B.
   */
  targetPersona?: (number | null) | Persona;
  problem?: (number | null) | Problem;
  seo?: {
    /**
     * Título para搜索引擎 (60 caracteres máx)
     */
    metaTitle?: string | null;
    /**
     * Descripción para搜索引擎 (160 caracteres máx)
     */
    metaDescription?: string | null;
    h1?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  priceRange?: {
    min?: number | null;
    max?: number | null;
    billingPeriod?: ('month' | 'service' | 'shift') | null;
    hidePrice?: boolean | null;
  };
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonials?: (number | Testimonial)[] | null;
  glmGenerated?: boolean | null;
  serperEnriched?: boolean | null;
  glmAnalysis?: {
    score?: number | null;
    opportunities?:
      | {
          opportunity?: string | null;
          id?: string | null;
        }[]
      | null;
    recommendedKeywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  glmGenerationStatus?: ('draft' | 'generating' | 'review_needed' | 'published') | null;
  /**
   * Mayor número = más importante para generar
   */
  priorityScore?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  views?: number | null;
  /**
   * Schema markup personalizado
   */
  schemaMarkup?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimonios de clientes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  company?: string | null;
  position?: string | null;
  testimonial: string;
  rating?: number | null;
  location?: (number | null) | Location;
  service?: (number | Service)[] | null;
  industry?: (number | null) | Industry;
  photo?: (number | null) | Media;
  videoUrl?: string | null;
  /**
   * Solo mostrar testimonios aprobados
   */
  isApproved?: boolean | null;
  /**
   * Mostrar en página principal
   */
  isFeatured?: boolean | null;
  useInHomepage?: boolean | null;
  useInLocationPages?: boolean | null;
  /**
   * Menor número = aparece primero
   */
  order?: number | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Keywords para SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: number;
  keyword: string;
  type: 'location' | 'service' | 'service-location' | 'problem-location' | 'long-tail';
  location?: (number | null) | Location;
  service?: (number | null) | Service;
  problem?: (number | null) | Problem;
  /**
   * Grupo de keywords relacionadas
   */
  cluster?: string | null;
  relatedKeywords?:
    | {
        keyword?: string | null;
        intent?: ('informational' | 'commercial' | 'transactional') | null;
        id?: string | null;
      }[]
    | null;
  intent?: ('informational' | 'commercial' | 'transactional') | null;
  serperMetrics?: {
    resultCount?: number | null;
    adsCount?: number | null;
    topCompetitors?:
      | {
          competitor?: string | null;
          position?: number | null;
          id?: string | null;
        }[]
      | null;
    searchedAt?: string | null;
  };
  glmAnalysis?: {
    difficulty?: number | null;
    volume?: ('high' | 'medium' | 'low') | null;
    opportunity?: ('high' | 'medium' | 'low') | null;
    recommendedUrl?: string | null;
    analyzedAt?: string | null;
  };
  isTracked?: boolean | null;
  targetPosition?: number | null;
  currentPosition?: number | null;
  priority?: ('high' | 'medium' | 'low') | null;
  seoPage?: (number | null) | SeoPage;
  createdAt: string;
  updatedAt: string;
}
/**
 * Leads captados desde formularios
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone: string;
  company?: string | null;
  message: string;
  source?: {
    /**
     * Página donde se captó el lead
     */
    pageUrl?: string | null;
    location?: (number | null) | Location;
    service?: (number | null) | Service;
    referrer?: string | null;
    normalizedPhone?: string | null;
    formId?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
  };
  /**
   * Datos preenchidos automaticamente pelo GLM
   */
  internalClassification?: {
    detectedPersona?: (number | null) | Persona;
    detectedProblems?: (number | Problem)[] | null;
    estimatedBudget?: ('low' | 'medium' | 'high' | 'enterprise') | null;
    urgency?: ('high' | 'medium' | 'low') | null;
    analyzedAt?: string | null;
    modelUsed?: string | null;
  };
  /**
   * Puntuación automática del lead
   */
  score?: number | null;
  smartAction?: ('URGENT_CONTACT' | 'FOLLOW_UP' | 'AI_DELEGATE' | 'REACTIVATE' | 'NOT_QUALIFIED') | null;
  /**
   * Estado del lead en el embudo
   */
  status?: ('new' | 'contacted' | 'quoting' | 'converted' | 'lost') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Vendedor responsable del lead
   */
  assignedTo?: (number | null) | User;
  notes?:
    | {
        note?: string | null;
        date?: string | null;
        user?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Historial de seguimientos
   */
  followUps?:
    | {
        date?: string | null;
        type?: ('call' | 'email' | 'whatsapp' | 'visit') | null;
        result?: ('no_answer' | 'interested' | 'not_interested' | 'callback') | null;
        nextAction?: string | null;
        nextFollowUp?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Si fue generado automáticamente por prospección
   */
  isAutoGenerated?: boolean | null;
  createdAt: string;
  updatedAt: string;
  lastContactedAt?: string | null;
  convertedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'prompts';
        value: number | Prompt;
      } | null)
    | ({
        relationTo: 'enrichment-history';
        value: number | EnrichmentHistory;
      } | null)
    | ({
        relationTo: 'api-cache';
        value: number | ApiCache;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'personas';
        value: number | Persona;
      } | null)
    | ({
        relationTo: 'problems';
        value: number | Problem;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'seo-pages';
        value: number | SeoPage;
      } | null)
    | ({
        relationTo: 'keywords';
        value: number | Keyword;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  phone?: T;
  isActive?: T;
  telegram?:
    | T
    | {
        chatId?: T;
        username?: T;
        notificationsEnabled?: T;
        notifyOnNewLead?: T;
        notifyOnStatusChange?: T;
      };
  salesProfile?:
    | T
    | {
        preferredZones?:
          | T
          | {
              zone?: T;
              id?: T;
            };
        specializations?:
          | T
          | {
              persona?: T;
              id?: T;
            };
        workingHours?:
          | T
          | {
              start?: T;
              end?: T;
            };
        maxPendingLeads?: T;
      };
  stats?:
    | T
    | {
        totalLeads?: T;
        convertedLeads?: T;
        conversionRate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts_select".
 */
export interface PromptsSelect<T extends boolean = true> {
  identifier?: T;
  description?: T;
  systemPrompt?: T;
  userPromptTemplate?: T;
  expectedOutputSchema?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrichment-history_select".
 */
export interface EnrichmentHistorySelect<T extends boolean = true> {
  sourceCollection?: T;
  sourceId?: T;
  serperRawData?: T;
  glmPromptIdentifier?: T;
  glmResponse?: T;
  tokensUsed?: T;
  wasSuccessful?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-cache_select".
 */
export interface ApiCacheSelect<T extends boolean = true> {
  cacheKey?: T;
  service?: T;
  response?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  featuredImage?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  priceRange?:
    | T
    | {
        min?: T;
        max?: T;
        billingPeriod?: T;
        hidePrice?: T;
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  relatedLocations?: T;
  relatedIndustries?: T;
  relatedProblems?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  isHighlighted?: T;
  isActive?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  image?: T;
  relatedServices?: T;
  targetPersonas?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  statistics?:
    | T
    | {
        marketSize?: T;
        growthRate?: T;
        mainRisks?:
          | T
          | {
              risk?: T;
              id?: T;
            };
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  caseStudy?: T;
  isActive?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  description?: T;
  avatar?: T;
  demographics?:
    | T
    | {
        ageRange?: T;
        location?: T;
        incomeLevel?: T;
      };
  painPoints?: T;
  needs?:
    | T
    | {
        need?: T;
        id?: T;
      };
  goals?:
    | T
    | {
        goal?: T;
        id?: T;
      };
  preferredServices?: T;
  budgetRange?:
    | T
    | {
        min?: T;
        max?: T;
      };
  decisionTimeline?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  relatedIndustries?: T;
  communication?:
    | T
    | {
        preferredChannel?: T;
        tone?: T;
      };
  scoring?:
    | T
    | {
        baseScore?: T;
        urgencyWeight?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems_select".
 */
export interface ProblemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  relatedServices?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        intent?: T;
        volume?: T;
        id?: T;
      };
  painPoints?:
    | T
    | {
        painPoint?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  image?: T;
  industry?: T;
  targetPersonas?: T;
  relatedServices?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        min?: T;
        max?: T;
        billingPeriod?: T;
        hidePrice?: T;
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  isHighlighted?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  geoZone?: T;
  tier?: T;
  economicDriver?: T;
  decisionBuyerLocation?: T;
  enrichmentStatus?: T;
  characteristics?: T;
  population?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  mainKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  serviceAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  priorityScore?: T;
  isActive?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-pages_select".
 */
export interface SeoPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  clusterRole?: T;
  parentHub?: T;
  location?: T;
  service?: T;
  industry?: T;
  persona?: T;
  targetPersona?: T;
  problem?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        h1?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        ctaText?: T;
        ctaLink?: T;
        backgroundImage?: T;
      };
  content?: T;
  highlights?:
    | T
    | {
        text?: T;
        icon?: T;
        id?: T;
      };
  priceRange?:
    | T
    | {
        min?: T;
        max?: T;
        billingPeriod?: T;
        hidePrice?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  testimonials?: T;
  glmGenerated?: T;
  serperEnriched?: T;
  glmAnalysis?:
    | T
    | {
        score?: T;
        opportunities?:
          | T
          | {
              opportunity?: T;
              id?: T;
            };
        recommendedKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  glmGenerationStatus?: T;
  priorityScore?: T;
  status?: T;
  publishedAt?: T;
  views?: T;
  schemaMarkup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords_select".
 */
export interface KeywordsSelect<T extends boolean = true> {
  keyword?: T;
  type?: T;
  location?: T;
  service?: T;
  problem?: T;
  cluster?: T;
  relatedKeywords?:
    | T
    | {
        keyword?: T;
        intent?: T;
        id?: T;
      };
  intent?: T;
  serperMetrics?:
    | T
    | {
        resultCount?: T;
        adsCount?: T;
        topCompetitors?:
          | T
          | {
              competitor?: T;
              position?: T;
              id?: T;
            };
        searchedAt?: T;
      };
  glmAnalysis?:
    | T
    | {
        difficulty?: T;
        volume?: T;
        opportunity?: T;
        recommendedUrl?: T;
        analyzedAt?: T;
      };
  isTracked?: T;
  targetPosition?: T;
  currentPosition?: T;
  priority?: T;
  seoPage?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  company?: T;
  position?: T;
  testimonial?: T;
  rating?: T;
  location?: T;
  service?: T;
  industry?: T;
  photo?: T;
  videoUrl?: T;
  isApproved?: T;
  isFeatured?: T;
  useInHomepage?: T;
  useInLocationPages?: T;
  order?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedLocations?: T;
  relatedServices?: T;
  relatedProblems?: T;
  author?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  status?: T;
  publishedAt?: T;
  featured?: T;
  views?: T;
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  message?: T;
  source?:
    | T
    | {
        pageUrl?: T;
        location?: T;
        service?: T;
        referrer?: T;
        normalizedPhone?: T;
        formId?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
      };
  internalClassification?:
    | T
    | {
        detectedPersona?: T;
        detectedProblems?: T;
        estimatedBudget?: T;
        urgency?: T;
        analyzedAt?: T;
        modelUsed?: T;
      };
  score?: T;
  smartAction?: T;
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  assignedTo?: T;
  notes?:
    | T
    | {
        note?: T;
        date?: T;
        user?: T;
        id?: T;
      };
  followUps?:
    | T
    | {
        date?: T;
        type?: T;
        result?: T;
        nextAction?: T;
        nextFollowUp?: T;
        id?: T;
      };
  isAutoGenerated?: T;
  createdAt?: T;
  updatedAt?: T;
  lastContactedAt?: T;
  convertedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * ADN de la marca, Asset Visuales (Logo/Favicon), Reglas para IA y Configuración de Negocio Local.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-dna".
 */
export interface BrandDna {
  id: number;
  /**
   * Meta description para SEO global
   */
  siteDescription?: string | null;
  companyName: string;
  legalName?: string | null;
  rut?: string | null;
  /**
   * Tono de voz que la IA debe usar (Ej: "B2B, profesional").
   */
  toneOfVoice: string;
  /**
   * Propuestas de valor clave (ej. "GuardPod autónomo").
   */
  coreDifferentiators: {
    differentiator: string;
    id?: string | null;
  }[];
  /**
   * Reglas invariables para GLM (ej. "Siempre nombrar OS-10").
   */
  strictRules: {
    rule: string;
    id?: string | null;
  }[];
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  favicon?: (number | null) | Media;
  colorPalette?: {
    primary?: string | null;
    secondary?: string | null;
    accent?: string | null;
  };
  headquartersAddress?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  primaryPhone?: string | null;
  whatsappNumber?: string | null;
  supportEmail?: string | null;
  businessHours?:
    | {
        day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
        /**
         * ej: 09:00
         */
        openTime?: string | null;
        /**
         * ej: 18:00
         */
        closeTime?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  glmConfig?: {
    model?: ('glm-5' | 'glm-4') | null;
    temperature?: number | null;
    maxTokens?: number | null;
  };
  limits?: {
    monthlySerperQuota?: number | null;
    monthlyGLMQuota?: number | null;
  };
  leadsConfig?: {
    autoAssign?: boolean | null;
    notifyTelegram?: boolean | null;
    scoringEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-dna_select".
 */
export interface BrandDnaSelect<T extends boolean = true> {
  siteDescription?: T;
  companyName?: T;
  legalName?: T;
  rut?: T;
  toneOfVoice?: T;
  coreDifferentiators?:
    | T
    | {
        differentiator?: T;
        id?: T;
      };
  strictRules?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  logo?: T;
  coverImage?: T;
  favicon?: T;
  colorPalette?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
      };
  headquartersAddress?: T;
  latitude?: T;
  longitude?: T;
  primaryPhone?: T;
  whatsappNumber?: T;
  supportEmail?: T;
  businessHours?:
    | T
    | {
        day?: T;
        openTime?: T;
        closeTime?: T;
        closed?: T;
        id?: T;
      };
  facebook?: T;
  instagram?: T;
  linkedin?: T;
  youtube?: T;
  glmConfig?:
    | T
    | {
        model?: T;
        temperature?: T;
        maxTokens?: T;
      };
  limits?:
    | T
    | {
        monthlySerperQuota?: T;
        monthlyGLMQuota?: T;
      };
  leadsConfig?:
    | T
    | {
        autoAssign?: T;
        notifyTelegram?: T;
        scoringEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}